/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Medicine {
  'id' : bigint,
  'packSize' : string,
  'name' : string,
  'description' : string,
  'company' : string,
  'strength' : string,
  'price' : bigint,
}
export interface MedicineItem { 'quantity' : bigint, 'medicineId' : bigint }
export interface OrderRecord {
  'id' : bigint,
  'status' : OrderStatus,
  'staffId' : Principal,
  'timestamp' : Time,
  'orderLines' : Array<MedicineItem>,
  'pharmacyId' : bigint,
}
export type OrderStatus = { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface Pharmacy {
  'id' : bigint,
  'contact' : string,
  'name' : string,
  'location' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addMedicine' : ActorMethod<
    [string, bigint, string, string, string, string],
    bigint
  >,
  'addPharmacy' : ActorMethod<[string, string, string], bigint>,
  'createOrder' : ActorMethod<[bigint, Array<MedicineItem>], bigint>,
  'deleteMedicine' : ActorMethod<[bigint], undefined>,
  'deletePharmacy' : ActorMethod<[bigint], undefined>,
  'getAllOrdersByStatus' : ActorMethod<[], Array<OrderRecord>>,
  'getAllStaffOrders' : ActorMethod<[], Array<OrderRecord>>,
  'getMedicines' : ActorMethod<[], Array<Medicine>>,
  'getOrder' : ActorMethod<[bigint], OrderRecord>,
  'getPharmacies' : ActorMethod<[], Array<Pharmacy>>,
  'getStaffOrders' : ActorMethod<[Principal], Array<OrderRecord>>,
  'registerStaff' : ActorMethod<[string, string], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];