/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Customer {
  'id' : bigint,
  'customerType' : CustomerType,
  'area' : string,
  'code' : string,
  'name' : string,
  'address' : string,
  'timestamp' : Time,
  'contactNo' : string,
  'groupName' : string,
}
export type CustomerType = { 'doctor' : null } |
  { 'medicalStore' : null } |
  { 'pharmacy' : null };
export interface Medicine {
  'id' : bigint,
  'packSize' : string,
  'name' : string,
  'description' : string,
  'company' : string,
  'strength' : string,
  'genericName' : string,
  'batchNo' : string,
  'price' : bigint,
  'medicineType' : string,
}
export interface MedicineItem {
  'distributionDiscount' : bigint,
  'companyDiscount' : bigint,
  'netRate' : bigint,
  'discountPercent' : bigint,
  'bonusQty' : bigint,
  'quantity' : bigint,
  'medicineId' : bigint,
}
export interface OrderRecord {
  'id' : bigint,
  'status' : OrderStatus,
  'staffCode' : string,
  'staffName' : string,
  'staffId' : Principal,
  'returnReason' : string,
  'pharmacyCode' : string,
  'notes' : string,
  'timestamp' : Time,
  'orderLines' : Array<MedicineItem>,
  'paymentReceived' : bigint,
  'pharmacyId' : bigint,
  'returnItems' : Array<ReturnItem>,
}
export type OrderStatus = { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface Pharmacy {
  'id' : bigint,
  'contact' : string,
  'code' : string,
  'name' : string,
  'location' : string,
}
export type Principal = Principal;
export interface PurchaseRecord {
  'id' : bigint,
  'packSize' : string,
  'productName' : string,
  'genericName' : string,
  'timestamp' : Time,
  'companyName' : string,
  'quantity' : bigint,
  'batchNo' : string,
  'price' : bigint,
  'medicineType' : string,
}
export interface ReturnItem { 'medicineId' : bigint, 'returnedQty' : bigint }
export type Time = bigint;
export interface _SERVICE {
  'addCustomer' : ActorMethod<
    [string, CustomerType, string, string, string, string, string],
    bigint
  >,
  'addMedicine' : ActorMethod<
    [string, bigint, string, string, string, string, string, string, string],
    bigint
  >,
  'addPharmacy' : ActorMethod<[string, string, string, string], bigint>,
  'addPurchase' : ActorMethod<
    [string, string, string, bigint, bigint, string, string, string],
    bigint
  >,
  'adjustInventoryStock' : ActorMethod<[bigint, bigint], boolean>,
  'createOrder' : ActorMethod<
    [bigint, Array<MedicineItem>, string, string],
    bigint
  >,
  'deleteCustomer' : ActorMethod<[bigint], boolean>,
  'deleteMedicine' : ActorMethod<[bigint], boolean>,
  'deletePharmacy' : ActorMethod<[bigint], boolean>,
  'deletePurchase' : ActorMethod<[bigint], boolean>,
  'getActiveOrders' : ActorMethod<[], Array<OrderRecord>>,
  'getAllStaffOrders' : ActorMethod<[], Array<OrderRecord>>,
  'getCustomers' : ActorMethod<[], Array<Customer>>,
  'getHistoryOrders' : ActorMethod<[], Array<OrderRecord>>,
  'getInventoryStock' : ActorMethod<[], Array<[bigint, bigint]>>,
  'getMedicines' : ActorMethod<[], Array<Medicine>>,
  'getOrder' : ActorMethod<[bigint], [] | [OrderRecord]>,
  'getPharmacies' : ActorMethod<[], Array<Pharmacy>>,
  'getPurchases' : ActorMethod<[], Array<PurchaseRecord>>,
  'getStaffOrders' : ActorMethod<[Principal], Array<OrderRecord>>,
  'registerStaff' : ActorMethod<[string, string], boolean>,
  'setInventoryStock' : ActorMethod<[bigint, bigint], boolean>,
  'updateOrderLines' : ActorMethod<
    [bigint, bigint, Array<MedicineItem>, string],
    boolean
  >,
  'updateOrderPaymentAndReturn' : ActorMethod<
    [bigint, bigint, Array<ReturnItem>, string, string],
    boolean
  >,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], boolean>,
  'verifyPassword' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];