/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MedicineItem = IDL.Record({
  'quantity' : IDL.Nat,
  'medicineId' : IDL.Nat,
});
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Time = IDL.Int;
export const OrderRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'staffId' : IDL.Principal,
  'timestamp' : Time,
  'orderLines' : IDL.Vec(MedicineItem),
  'pharmacyId' : IDL.Nat,
});
export const Medicine = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});
export const Pharmacy = IDL.Record({
  'id' : IDL.Nat,
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'addMedicine' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'addPharmacy' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'createOrder' : IDL.Func([IDL.Nat, IDL.Vec(MedicineItem)], [IDL.Nat], []),
  'getAllOrdersByStatus' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
  'getAllStaffOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
  'getMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [OrderRecord], ['query']),
  'getPharmacies' : IDL.Func([], [IDL.Vec(Pharmacy)], ['query']),
  'getStaffOrders' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(OrderRecord)],
      ['query'],
    ),
  'registerStaff' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MedicineItem = IDL.Record({
    'quantity' : IDL.Nat,
    'medicineId' : IDL.Nat,
  });
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Time = IDL.Int;
  const OrderRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'staffId' : IDL.Principal,
    'timestamp' : Time,
    'orderLines' : IDL.Vec(MedicineItem),
    'pharmacyId' : IDL.Nat,
  });
  const Medicine = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Pharmacy = IDL.Record({
    'id' : IDL.Nat,
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'addMedicine' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'addPharmacy' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'createOrder' : IDL.Func([IDL.Nat, IDL.Vec(MedicineItem)], [IDL.Nat], []),
    'getAllOrdersByStatus' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
    'getAllStaffOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
    'getMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [OrderRecord], ['query']),
    'getPharmacies' : IDL.Func([], [IDL.Vec(Pharmacy)], ['query']),
    'getStaffOrders' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(OrderRecord)],
        ['query'],
      ),
    'registerStaff' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };